### ISSUE TITLE
Background layout color ERROR

### ISSUE THREAD

**Issue by MrKarlsonCloud** [Qognica/qognicafinance-react-lightweight-charts#6]
**Describe the bug**
I have problem when I want to change background layout color. Exist only white color and the code doesn't change with another color.

**To Reproduce**
Try change background layout color and you will see

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by axdra** [comment]
Can not reproduce this bug, it is possible to change color of the background.

This example works; 
```ts
<Chart options={{
  layout: {
  backgroundColor: '#000'
  }}
...
/>

**Comment by axdra** [comment]
If this does not help, please reopen issue.

**Comment by MrKarlsonCloud** [comment]
Yes, thank you for helping. But you can reproduce the error with that.

![image](https://user-images.githubusercontent.com/43963099/150092067-dc876056-c7bf-40bb-8a2c-3b95fbfb2549.png)

You can see in that image that I use "**backgroundColor**" for light "mode" but if I want to change dark "mode" I need add "**background**" key for that.  By the moment I fixed my issue with image example but I think it is a bug.

**Comment by MrKarlsonCloud** [comment]
@axdra Sorry doesn't work. Try with another colour and you will see :) with my examples you can reproduce that issue.

I think it's working wrong with darktheme and light theme ;)
