### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by venables** [Qognica/qognicafinance-react-lightweight-charts#7]
**Describe the bug**
There's a peerDependency on react ^17

**To Reproduce**
Install on a react 18 project

**Expected behavior**
Ideally we can use this library with React 18

**Comment by benjaminchevoor** [comment]
Opened a PR here: https://github.com/Qognica/qognicafinance-react-lightweight-charts/pull/8

**Comment by SimonDamberg** [comment]
Fixed with #8, thanks for reporting!
